# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refactoring', '0003_solution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set([('code', 'creator', 'exercise')]),
        ),
    ]
