# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactoring', '0004_auto_20170216_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='serial_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
