# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refactoring', '0005_solution_serial_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('serial_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_text',
        ),
        migrations.AddField(
            model_name='step',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactoring.Exercise'),
        ),
    ]
