# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refactoring', '0006_auto_20170331_1853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set([('code', 'tests', 'session'), ('serial_id', 'session')]),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('serial_id', 'exercise')]),
        ),
    ]
